feat: add plugin cli to docker image
pact-foundation/pact-ruby-cli pull request #86
Opened 2022-12-20 02:45 UTC by rholshausen

This adds the plugin CLI into the docker image.

However, I don't think this is useful. By default, it will install any plugin into the container, which is not what anyone would want. Users will need to mount the plugin installation directory and then set an environment variable just to get it to work. And it will then only install the Linux version of the plugins.

2022-12-20 02:56 UTC, mefellows commented
> However, I don't think this is useful. By default, it will install any plugin into the container, which is not what anyone would want. Users will need to mount the plugin installation directory and then set an environment variable just to get it to work. And it will then only install the Linux version of the plugins.

Ah, but you're forgetting about the next feature request "how can I run the plugin inside docker?" :trollface:.

So yes, this doesn't exactly feel useful. 

The more and more we do this, the more I'm seeing the value in replacing our Ruby CLI with a cross-compilable one (e.g. Rust) that can be easily installed across most OS/Arch combinations, and downloaded via the common `curl getpact.sh | bash` type thing.

Is there any value in merging this? For example, if flags could be passed to the plugin CLI (in a future change) to override the OS/Arch would that make this useful?

2023-01-09 23:44 UTC, bethesque commented
I think we don't add it until someone asks for it.

2023-05-10 11:39 UTC, YOU54F requested changes
Agree that this isn't going to be useful, for installing plugins for a user, or using them via Docker.

looking at the commands, `pact-plugin-cli list known` and maybe some of the `repository` commands

```
Usage: pact-plugin-cli repository <COMMAND>

Commands:
  validate                 Check the consistency of the repository index file
  new                      Create a new blank repository index file
  add-plugin-version       Add a plugin version to the index file (will update existing entry)
  add-all-plugin-versions  Add all versions of a plugin to the index file (will update existing entries)
  yank-version             Remove a plugin version from the index file
  list                     List all plugins found in the index file
  list-versions            List all plugin versions found in the index file
  help                     Print this message or the help of the given subcommand(s)
```

Should we just close this PR down, to avoid repo noise, and if a user comes up with a use case, we can revisit (probably with a different approach/image or whatever)

As the CLI can be installed as a binary on the host machine where it needs to have the plugins installed, it makes sense to make that available via a script or package manager rather than distribute via docker.

There might be a necessity for a user to run a plugin in docker, as part of running their tests, but they can just install it as a pre-req (or ideally the test framework deals with it) - but we do know users suffer from proxy woes so need to have things pre-installed rather than reaching out)

2023-05-10 11:42 UTC, mefellows commented
I think we close it for now. The only way I think we could make it work is:

1. Add some additional flags to override the OS/arch detection (otherwise it will default to the same as the Docker image)
2. Advise people to mount the `~/.pact` directory (or again, provide a flag to specify another mapped volume mount)

2023-05-30 02:18 UTC, closed without merging